"""add_stock_num_to_material

Revision ID: 0c39d2c5df1c
Revises: cc49d9ce0732
Create Date: 2017-04-30 14:09:43.094805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c39d2c5df1c'
down_revision = 'cc49d9ce0732'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material', sa.Column('stock_num', sa.Integer(), nullable=True))
    op.add_column('material_application', sa.Column('app_memo', sa.String(length=500), nullable=True))
    op.add_column('material_application_content', sa.Column('material_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'material_application_content', 'material', ['material_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'material_application_content', type_='foreignkey')
    op.drop_column('material_application_content', 'material_id')
    op.drop_column('material_application', 'app_memo')
    op.drop_column('material', 'stock_num')
    # ### end Alembic commands ###
