"""add extra_attributes to user_info

Revision ID: 1bbc1621f6d4
Revises: ef83fe89b1ed
Create Date: 2017-04-26 15:00:17.054140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bbc1621f6d4'
down_revision = 'ef83fe89b1ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_infos', sa.Column('extra_attributes', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_infos', 'extra_attributes')
    # ### end Alembic commands ###
