"""add_status_to_tracking_info

Revision ID: 1d565073bb01
Revises: bb09c512cfd0
Create Date: 2017-03-05 13:30:40.956928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d565073bb01'
down_revision = 'bb09c512cfd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracking_info', sa.Column('status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracking_info', 'status')
    # ### end Alembic commands ###
