"""add square_num

Revision ID: 2372f1f8d894
Revises: c7bccccf81a5
Create Date: 2017-02-23 06:05:01.001318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2372f1f8d894'
down_revision = 'c7bccccf81a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_contents', sa.Column('square_num', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_contents', 'square_num')
    # ### end Alembic commands ###
