"""empty message

Revision ID: 2ac2afb55e48
Revises: 0c39d2c5df1c
Create Date: 2017-05-02 11:09:41.403575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ac2afb55e48'
down_revision = '0c39d2c5df1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracking_info', sa.Column('qrcode_scan_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracking_info', 'qrcode_scan_date')
    # ### end Alembic commands ###
