"""empty message

Revision ID: 33f0e654700f
Revises: 2d1bf125618d
Create Date: 2017-05-02 14:39:53.742110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33f0e654700f'
down_revision = '2d1bf125618d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_infos', 'extra_attributes')
    op.add_column('users', sa.Column('extra_attributes', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'extra_attributes')
    op.add_column('user_infos', sa.Column('extra_attributes', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
