"""add memo to material application

Revision ID: 3f632ce96098
Revises: 65376f05aa12
Create Date: 2017-02-23 23:29:28.258296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f632ce96098'
down_revision = '65376f05aa12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material_application', sa.Column('memo', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('material_application', 'memo')
    # ### end Alembic commands ###
