"""create_web_access_log

Revision ID: 483fbd912e83
Revises: cfd51dd8aaa0
Create Date: 2017-03-20 13:40:01.592316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '483fbd912e83'
down_revision = 'c5106cf0f74c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('web_access_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_path', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('remote_addr', sa.String(length=15), nullable=True),
    sa.Column('user_agent', sa.String(length=200), nullable=True),
    sa.Column('platform', sa.String(length=20), nullable=True),
    sa.Column('browser', sa.String(length=20), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('web_access_log')
    # ### end Alembic commands ###
