"""empty message

Revision ID: 59eeab2bbaaf
Revises: d80a29ceb22a
Create Date: 2017-03-03 09:31:18.365338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59eeab2bbaaf'
down_revision = 'd80a29ceb22a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wechat_access_token', sa.Column('appid', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wechat_access_token', 'appid')
    # ### end Alembic commands ###
