"""create_material_application_models

Revision ID: 65376f05aa12
Revises: ad50d4738049
Create Date: 2017-02-23 17:31:22.398052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65376f05aa12'
down_revision = 'ad50d4738049'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('material_application_content', sa.Column('material_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'material_application_content', 'material', ['material_id'], ['id'])
    op.drop_column('material_application_content', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material_application_content', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'material_application_content', type_='foreignkey')
    op.drop_column('material_application_content', 'material_id')
    op.drop_table('material')
    # ### end Alembic commands ###
