"""empty message

Revision ID: 7939e3b94900
Revises: ea68faadfa4e
Create Date: 2017-03-02 09:54:14.272255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7939e3b94900'
down_revision = 'ea68faadfa4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wechat_access_token', 'access_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wechat_access_token', sa.Column('access_token', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
