"""add audit_content to project report

Revision ID: 901a4674cb12
Revises: 96560e166b50
Create Date: 2017-03-06 11:01:19.713768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '901a4674cb12'
down_revision = '96560e166b50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_reports', sa.Column('audit_content', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_reports', 'audit_content')
    # ### end Alembic commands ###
