"""add report_no to project report

Revision ID: 96560e166b50
Revises: c0778ba000bb
Create Date: 2017-03-06 09:31:37.521990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96560e166b50'
down_revision = 'c0778ba000bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_reports', sa.Column('report_no', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_reports', 'report_no')
    # ### end Alembic commands ###
