"""empty message

Revision ID: 9cc62ef23a49
Revises: 9101b893be5c
Create Date: 2017-02-19 09:41:57.762816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cc62ef23a49'
down_revision = '9101b893be5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('districts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('person_in_charge', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dealers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_no', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('dealer_id', sa.Integer(), nullable=True),
    sa.Column('order_status', sa.String(length=50), nullable=True),
    sa.Column('order_memo', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_no')
    )
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_no', sa.String(length=30), nullable=True),
    sa.Column('contract_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('contract_status', sa.String(length=50), nullable=True),
    sa.Column('product_status', sa.String(length=50), nullable=True),
    sa.Column('shipment_status', sa.String(length=50), nullable=True),
    sa.Column('contract_content', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_no')
    )
    op.create_table('order_contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(length=300), nullable=True),
    sa.Column('sku_specification', sa.String(length=500), nullable=True),
    sa.Column('sku_code', sa.String(length=30), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('square_num', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_contents')
    op.drop_table('contracts')
    op.drop_table('orders')
    op.drop_table('dealers')
    op.drop_table('districts')
    # ### end Alembic commands ###
