"""add_parent_id_to_users_and_sales_areas

Revision ID: 9fea66319b4a
Revises: 5705eb7a8dcf
Create Date: 2017-03-10 10:02:08.760531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fea66319b4a'
down_revision = '5705eb7a8dcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_and_sales_areas', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('users_and_sales_areas', sa.Column('parent_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_and_sales_areas', 'parent_time')
    op.drop_column('users_and_sales_areas', 'parent_id')
    # ### end Alembic commands ###
