"""add product ids to contents

Revision ID: a2c6970d8137
Revises: 0ad45412bffd
Create Date: 2017-02-22 15:02:32.385131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2c6970d8137'
down_revision = '0ad45412bffd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content', sa.Column('product_ids', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content', 'product_ids')
    # ### end Alembic commands ###
