"""add_token_type_to_wechat_access_token

Revision ID: a4ef5d3cfd2a
Revises: 59eeab2bbaaf
Create Date: 2017-03-03 13:26:06.810849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4ef5d3cfd2a'
down_revision = '59eeab2bbaaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wechat_access_token', sa.Column('token_type', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wechat_access_token', 'token_type')
    # ### end Alembic commands ###
