"""create_tracking_info_and_design_application

Revision ID: bb09c512cfd0
Revises: a4ef5d3cfd2a
Create Date: 2017-03-04 21:18:09.511320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb09c512cfd0'
down_revision = 'a4ef5d3cfd2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracking_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_no', sa.String(length=50), nullable=True),
    sa.Column('contract_date', sa.DateTime(), nullable=True),
    sa.Column('receiver_name', sa.String(length=200), nullable=True),
    sa.Column('receiver_tel', sa.String(length=30), nullable=True),
    sa.Column('production_date', sa.DateTime(), nullable=True),
    sa.Column('delivery_date', sa.DateTime(), nullable=True),
    sa.Column('delivery_plate_no', sa.String(length=100), nullable=True),
    sa.Column('delivery_man_tel', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('design_application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filing_no', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('ul_file', sa.String(length=200), nullable=True),
    sa.Column('dl_file', sa.String(length=200), nullable=True),
    sa.Column('applicant_id', sa.Integer(), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracking_info_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('tracking_info_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tracking_info_id'], ['tracking_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracking_info_detail')
    op.drop_table('design_application')
    op.drop_table('tracking_info')
    # ### end Alembic commands ###
