"""add price info to order content

Revision ID: bcbb13072ffa
Revises: 0dcc2e844976
Create Date: 2017-02-23 03:57:32.016026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcbb13072ffa'
down_revision = '0dcc2e844976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_contents', sa.Column('amount', sa.Float(), nullable=True))
    op.add_column('order_contents', sa.Column('memo', sa.String(length=100), nullable=True))
    op.add_column('order_contents', sa.Column('price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_contents', 'price')
    op.drop_column('order_contents', 'memo')
    op.drop_column('order_contents', 'amount')
    # ### end Alembic commands ###
