"""add_user_id_to_contracts

Revision ID: c2024ad11427
Revises: 131e90437d13
Create Date: 2017-03-09 16:22:03.810885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2024ad11427'
down_revision = '131e90437d13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'contracts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contracts', type_='foreignkey')
    op.drop_column('contracts', 'user_id')
    # ### end Alembic commands ###
