"""add WechatUserInfo for wechat user binding

Revision ID: c5106cf0f74c
Revises: cfd51dd8aaa0
Create Date: 2017-03-20 10:54:23.348829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5106cf0f74c'
down_revision = 'cfd51dd8aaa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wechat_user_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('open_id', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('active_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wechat_user_info')
    # ### end Alembic commands ###
