"""add batch info to order_content

Revision ID: c6fb90a99137
Revises: 483fbd912e83
Create Date: 2017-03-23 16:44:57.607788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6fb90a99137'
down_revision = '483fbd912e83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_contents', sa.Column('batch_info', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_contents', 'batch_info')
    # ### end Alembic commands ###
