"""change square from integer to float #1

Revision ID: c7bccccf81a5
Revises: bcbb13072ffa
Create Date: 2017-02-23 05:56:42.919800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7bccccf81a5'
down_revision = 'bcbb13072ffa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_contents', 'square_num')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_contents', sa.Column('square_num', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
