"""add sale_contract to order

Revision ID: e32af8c8d78a
Revises: 9fea66319b4a
Create Date: 2017-03-16 21:05:30.065102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e32af8c8d78a'
down_revision = '9fea66319b4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('sale_contract', sa.String(length=200), nullable=True))
    op.add_column('orders', sa.Column('sale_contract_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'sale_contract_id')
    op.drop_column('orders', 'sale_contract')
    # ### end Alembic commands ###
