"""add_app_type_to_material_application

Revision ID: e956ef9ac5fc
Revises: 30bb070970b9
Create Date: 2017-05-14 12:29:52.839022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e956ef9ac5fc'
down_revision = '30bb070970b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material_application', sa.Column('app_infos', sa.JSON(), nullable=True))
    op.add_column('material_application', sa.Column('app_type', sa.Integer(), nullable=True))
    op.add_column('material_application', sa.Column('sales_area', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('material_application', 'sales_area')
    op.drop_column('material_application', 'app_type')
    op.drop_column('material_application', 'app_infos')
    # ### end Alembic commands ###
