"""add_dl_file_memo_to_design_application

Revision ID: ef83fe89b1ed
Revises: 31300aea2b2b
Create Date: 2017-04-20 17:11:48.703407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef83fe89b1ed'
down_revision = '31300aea2b2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('design_application', sa.Column('dl_file_memo', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('design_application', 'dl_file_memo')
    # ### end Alembic commands ###
