"""empty message

Revision ID: f96e60b9c39c
Revises: f4c99095e70c
Create Date: 2017-03-29 10:56:58.670182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f96e60b9c39c'
down_revision = 'f4c99095e70c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wechat_push_msg', 'push_flag',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wechat_push_msg', 'push_flag',
               existing_type=sa.String(length=10),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    # ### end Alembic commands ###
